import styled from 'styled-components';

export const Container = styled.div`
  width: 100%;
  height: 300px;
  display: flex;
  align-items: center;
  justify-content: center;

  @keyframes ldio-tubwdlfop {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
  .ldio-tubwdlfop div {
    position: absolute;
    width: 60px;
    height: 60px;
    border: 10px solid #78d98a;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-tubwdlfop div {
    animation: ldio-tubwdlfop 1s linear infinite;
    top: 50px;
    left: 50px;
  }
  .loadingio-spinner-rolling-bysz75b0qa {
    width: 100px;
    height: 100px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
  }
  .ldio-tubwdlfop {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-tubwdlfop div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
